name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: slack-send
      - uses: slackapi/slack-github-action@v1.15.0
      - with:
          channel-id: C02DGE4CBF
          slack-message: Slack message test, an PR was opened! # optional
