name: jira_isue
on:
  issues:
     types: [opened, edited]
  workflow_dispatch:
  
jobs:
  jira_login:
    runs-on: ubuntu-latest
    steps:
      - name: Jira Login
        uses: atlassian/gajira-login@v2.0.0
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - name: Jira Create issue
        uses: atlassian/gajira-create@v2.0.1
        with:
          # Key of the project
          project: GIT
          # Type of the issue to be created. Example: 'Incident'
          issuetype: Bug
          # Issue summary
          summary: ${{github.event.issue.title}}
          # Issue description
          description: description test

