
name: slack

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - name: slack-send
        uses: slackapi/slack-github-action@v1.15.0
        with:
          channel-id: C02DGE4CBFY
          slack-message: New Pull request to the ${{github.repository}} From Branch${{github.head_ref}} To ${{github.base_ref}}  #### ${{github.event.pull_request.title}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_TOKEN }}
